- name: Generate fallback filename
  ansible.builtin.set_fact:
    apt_deb822_filename_fallback: |-
      {{
        apt_deb822_filename |
        default(
          apt_deb822_options.URIs |
          first |
          regex_replace('([^@]+)$', '\1') |
          regex_replace('[^a-zA-Z0-9]+', '_') |
          regex_replace('_$', '')
        )
      }}
  when: not apt_deb822_filename is defined
  tags:
    - repo
    - apt_deb822

- name: Deploy deb822 repository file
  template:
    src: deb822.sources.j2
    dest: "{{ apt_deb822_sources_dir }}/{{ apt_deb822_filename | default( apt_deb822_filename_fallback ) }}.sources"
    mode: "{{ apt_deb822_mode | default ( apt_deb822_mode_default ) }}"
  when: apt_deb822_state | default( 'present' ) != "absent"
  tags:
    - repo
    - apt_deb822

- name: Remove deb822 repository file
  file:
    dest: "{{ apt_deb822_sources_dir }}/{{ apt_deb822_filename | default( apt_deb822_filename_fallback ) }}.sources"
    state: absent
  when: apt_deb822_state | default( 'present' ) == "absent"
  tags:
    - repo
    - apt_deb822
